// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MyExternalMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MyExternalMessage.proto</summary>
public static partial class MyExternalMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for MyExternalMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MyExternalMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdNeUV4dGVybmFsTWVzc2FnZS5wcm90byKNAQoRTXlFeHRlcm5hbE1lc3Nh",
          "Z2USDwoHY21kQ29kZRgBIAEoBRIWCg5wcm90b2NvbFN3aXRjaBgCIAEoBRIQ",
          "CghjbWRNZXJnZRgDIAEoBRIWCg5yZXNwb25zZVN0YXR1cxgEIAEoERIQCgh2",
          "YWxpZE1zZxgFIAEoCRITCgtkYXRhQ29udGVudBgGIAEoDGIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MyExternalMessage), global::MyExternalMessage.Parser, new[]{ "CmdCode", "ProtocolSwitch", "CmdMerge", "ResponseStatus", "ValidMsg", "DataContent" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 结果
/// </summary>
public sealed partial class MyExternalMessage : pb::IMessage<MyExternalMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MyExternalMessage> _parser = new pb::MessageParser<MyExternalMessage>(() => new MyExternalMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MyExternalMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MyExternalMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MyExternalMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MyExternalMessage(MyExternalMessage other) : this() {
    cmdCode_ = other.cmdCode_;
    protocolSwitch_ = other.protocolSwitch_;
    cmdMerge_ = other.cmdMerge_;
    responseStatus_ = other.responseStatus_;
    validMsg_ = other.validMsg_;
    dataContent_ = other.dataContent_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MyExternalMessage Clone() {
    return new MyExternalMessage(this);
  }

  /// <summary>Field number for the "cmdCode" field.</summary>
  public const int CmdCodeFieldNumber = 1;
  private int cmdCode_;
  /// <summary>
  /// 请求命令类型: 0 心跳，1 业务
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CmdCode {
    get { return cmdCode_; }
    set {
      cmdCode_ = value;
    }
  }

  /// <summary>Field number for the "protocolSwitch" field.</summary>
  public const int ProtocolSwitchFieldNumber = 2;
  private int protocolSwitch_;
  /// <summary>
  /// 协议开关，用于一些协议级别的开关控制，比如 安全加密校验等。 : 0 不校验
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ProtocolSwitch {
    get { return protocolSwitch_; }
    set {
      protocolSwitch_ = value;
    }
  }

  /// <summary>Field number for the "cmdMerge" field.</summary>
  public const int CmdMergeFieldNumber = 3;
  private int cmdMerge_;
  /// <summary>
  /// 业务路由（高16为主, 低16为子）
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CmdMerge {
    get { return cmdMerge_; }
    set {
      cmdMerge_ = value;
    }
  }

  /// <summary>Field number for the "responseStatus" field.</summary>
  public const int ResponseStatusFieldNumber = 4;
  private int responseStatus_;
  /// <summary>
  /// 响应码: 0:成功, 其他为有错误
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ResponseStatus {
    get { return responseStatus_; }
    set {
      responseStatus_ = value;
    }
  }

  /// <summary>Field number for the "validMsg" field.</summary>
  public const int ValidMsgFieldNumber = 5;
  private string validMsg_ = "";
  /// <summary>
  /// 验证信息: 当 responseStatus == -1001 时， 会有值
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ValidMsg {
    get { return validMsg_; }
    set {
      validMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dataContent" field.</summary>
  public const int DataContentFieldNumber = 6;
  private pb::ByteString dataContent_ = pb::ByteString.Empty;
  /// <summary>
  /// 业务请求数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString DataContent {
    get { return dataContent_; }
    set {
      dataContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MyExternalMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MyExternalMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CmdCode != other.CmdCode) return false;
    if (ProtocolSwitch != other.ProtocolSwitch) return false;
    if (CmdMerge != other.CmdMerge) return false;
    if (ResponseStatus != other.ResponseStatus) return false;
    if (ValidMsg != other.ValidMsg) return false;
    if (DataContent != other.DataContent) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CmdCode != 0) hash ^= CmdCode.GetHashCode();
    if (ProtocolSwitch != 0) hash ^= ProtocolSwitch.GetHashCode();
    if (CmdMerge != 0) hash ^= CmdMerge.GetHashCode();
    if (ResponseStatus != 0) hash ^= ResponseStatus.GetHashCode();
    if (ValidMsg.Length != 0) hash ^= ValidMsg.GetHashCode();
    if (DataContent.Length != 0) hash ^= DataContent.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (CmdCode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(CmdCode);
    }
    if (ProtocolSwitch != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ProtocolSwitch);
    }
    if (CmdMerge != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CmdMerge);
    }
    if (ResponseStatus != 0) {
      output.WriteRawTag(32);
      output.WriteSInt32(ResponseStatus);
    }
    if (ValidMsg.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ValidMsg);
    }
    if (DataContent.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(DataContent);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (CmdCode != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(CmdCode);
    }
    if (ProtocolSwitch != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ProtocolSwitch);
    }
    if (CmdMerge != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(CmdMerge);
    }
    if (ResponseStatus != 0) {
      output.WriteRawTag(32);
      output.WriteSInt32(ResponseStatus);
    }
    if (ValidMsg.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(ValidMsg);
    }
    if (DataContent.Length != 0) {
      output.WriteRawTag(50);
      output.WriteBytes(DataContent);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CmdCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CmdCode);
    }
    if (ProtocolSwitch != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProtocolSwitch);
    }
    if (CmdMerge != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(CmdMerge);
    }
    if (ResponseStatus != 0) {
      size += 1 + pb::CodedOutputStream.ComputeSInt32Size(ResponseStatus);
    }
    if (ValidMsg.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ValidMsg);
    }
    if (DataContent.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(DataContent);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MyExternalMessage other) {
    if (other == null) {
      return;
    }
    if (other.CmdCode != 0) {
      CmdCode = other.CmdCode;
    }
    if (other.ProtocolSwitch != 0) {
      ProtocolSwitch = other.ProtocolSwitch;
    }
    if (other.CmdMerge != 0) {
      CmdMerge = other.CmdMerge;
    }
    if (other.ResponseStatus != 0) {
      ResponseStatus = other.ResponseStatus;
    }
    if (other.ValidMsg.Length != 0) {
      ValidMsg = other.ValidMsg;
    }
    if (other.DataContent.Length != 0) {
      DataContent = other.DataContent;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          CmdCode = input.ReadInt32();
          break;
        }
        case 16: {
          ProtocolSwitch = input.ReadInt32();
          break;
        }
        case 24: {
          CmdMerge = input.ReadInt32();
          break;
        }
        case 32: {
          ResponseStatus = input.ReadSInt32();
          break;
        }
        case 42: {
          ValidMsg = input.ReadString();
          break;
        }
        case 50: {
          DataContent = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          CmdCode = input.ReadInt32();
          break;
        }
        case 16: {
          ProtocolSwitch = input.ReadInt32();
          break;
        }
        case 24: {
          CmdMerge = input.ReadInt32();
          break;
        }
        case 32: {
          ResponseStatus = input.ReadSInt32();
          break;
        }
        case 42: {
          ValidMsg = input.ReadString();
          break;
        }
        case 50: {
          DataContent = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
